INSERT INTO packs (id, user_id, name) VALUES (1, 'me', '[LOOPS] ug melodies - @luvbesly (july-aug)');
INSERT INTO contacts (id, user_id, name, type, subgenre, listeners, twitter, instagram, discord, email, notes) VALUES (1, 'me', 'wyrdo', 'prod+artist', 'melodic rage', 17000, '@usowyrd', NULL, NULL, NULL, NULL);
INSERT INTO contacts (id, user_id, name, type, subgenre, listeners, twitter, instagram, discord, email, notes) VALUES (2, 'me', 'azure', 'prod', 'rage', NULL, '@azureisdead', NULL, NULL, NULL, NULL);
INSERT INTO contacts (id, user_id, name, type, subgenre, listeners, twitter, instagram, discord, email, notes) VALUES (3, 'me', 'warrenhunter', 'prod', 'rage', NULL, '@warrenhunter', NULL, NULL, NULL, NULL);
INSERT INTO contacts (id, user_id, name, type, subgenre, listeners, twitter, instagram, discord, email, notes) VALUES (4, 'me', 'warpstr', 'prod', NULL, NULL, '@warpstrr', NULL, NULL, NULL, NULL);
INSERT INTO contacts (id, user_id, name, type, subgenre, listeners, twitter, instagram, discord, email, notes) VALUES (5, 'me', 'repglick', 'prod', NULL, NULL, '@repglick', NULL, NULL, NULL, NULL);
INSERT INTO contacts (id, user_id, name, type, subgenre, listeners, twitter, instagram, discord, email, notes) VALUES (6, 'me', 'ss3bby', 'prod', NULL, NULL, '@ss3bby1c', NULL, NULL, NULL, NULL);
INSERT INTO contacts (id, user_id, name, type, subgenre, listeners, twitter, instagram, discord, email, notes) VALUES (7, 'me', 'phreshboyswag', 'artist', NULL, 197000, '@phreshboyswag', NULL, NULL, NULL, NULL);
INSERT INTO contacts (id, user_id, name, type, subgenre, listeners, twitter, instagram, discord, email, notes) VALUES (8, 'me', 'gyro', 'prod', 'rage', NULL, '@xxgyro', NULL, NULL, NULL, NULL);
INSERT INTO contacts (id, user_id, name, type, subgenre, listeners, twitter, instagram, discord, email, notes) VALUES (9, 'me', 'ginseng', 'prod', 'pinknoise', NULL, '@ginsengggggg', NULL, NULL, NULL, NULL);
INSERT INTO contacts (id, user_id, name, type, subgenre, listeners, twitter, instagram, discord, email, notes) VALUES (10, 'me', 'misogi', 'prod', 'pinknoise', NULL, '@xxmisogi', NULL, NULL, NULL, NULL);
INSERT INTO contacts (id, user_id, name, type, subgenre, listeners, twitter, instagram, discord, email, notes) VALUES (11, 'me', '177p', 'prod', NULL, NULL, '@177p1', NULL, NULL, NULL, NULL);
INSERT INTO contacts (id, user_id, name, type, subgenre, listeners, twitter, instagram, discord, email, notes) VALUES (12, 'me', '9lives', 'prod', NULL, NULL, '@rip9lives', NULL, NULL, NULL, NULL);
INSERT INTO contacts (id, user_id, name, type, subgenre, listeners, twitter, instagram, discord, email, notes) VALUES (13, 'me', 'blxty', 'prod', NULL, NULL, '@blxty', NULL, NULL, NULL, NULL);
INSERT INTO contacts (id, user_id, name, type, subgenre, listeners, twitter, instagram, discord, email, notes) VALUES (14, 'me', 'ivvys', 'prod', NULL, NULL, '@eyeveeswun', NULL, NULL, NULL, NULL);
INSERT INTO contacts (id, user_id, name, type, subgenre, listeners, twitter, instagram, discord, email, notes) VALUES (15, 'me', 'yk', 'prod', NULL, NULL, '@ykwakeup', NULL, NULL, NULL, NULL);
INSERT INTO contacts (id, user_id, name, type, subgenre, listeners, twitter, instagram, discord, email, notes) VALUES (16, 'me', 'Heavengazer', 'prod', NULL, NULL, '@heavengazerrr', NULL, NULL, NULL, NULL);
INSERT INTO contacts (id, user_id, name, type, subgenre, listeners, twitter, instagram, discord, email, notes) VALUES (17, 'me', 'jackzebra', 'artist', NULL, 82000, '@jackzebra626', NULL, NULL, NULL, NULL);
INSERT INTO contacts (id, user_id, name, type, subgenre, listeners, twitter, instagram, discord, email, notes) VALUES (18, 'me', 'elxnce', 'prod', NULL, NULL, '@elxnce', NULL, NULL, NULL, NULL);
INSERT INTO contacts (id, user_id, name, type, subgenre, listeners, twitter, instagram, discord, email, notes) VALUES (19, 'me', 'heroine', 'prod', NULL, NULL, '@tatertot', NULL, NULL, NULL, NULL);
INSERT INTO contacts (id, user_id, name, type, subgenre, listeners, twitter, instagram, discord, email, notes) VALUES (20, 'me', 'kuru', 'prod+artist', NULL, 300000, '@kuru8k', NULL, NULL, NULL, NULL);
INSERT INTO contacts (id, user_id, name, type, subgenre, listeners, twitter, instagram, discord, email, notes) VALUES (21, 'me', 'mh', 'prod', NULL, NULL, '@prodmhh', NULL, NULL, NULL, NULL);
INSERT INTO contacts (id, user_id, name, type, subgenre, listeners, twitter, instagram, discord, email, notes) VALUES (22, 'me', 'SILENTHEAVEN', 'prod', NULL, NULL, '@MYSILENTHEAVEN', NULL, NULL, NULL, NULL);
INSERT INTO contacts (id, user_id, name, type, subgenre, listeners, twitter, instagram, discord, email, notes) VALUES (23, 'me', 'sjr', 'prod', NULL, NULL, '@sjr2800', NULL, NULL, NULL, NULL);
INSERT INTO contacts (id, user_id, name, type, subgenre, listeners, twitter, instagram, discord, email, notes) VALUES (24, 'me', 'Syzy', 'prod', NULL, NULL, '@syzymusic', NULL, NULL, NULL, NULL);
INSERT INTO sends (user_id, contact_id, pack_id, channel, sent_at, status) VALUES ('me', 24, 1, 'tw', '2026-08-27', 'pendiente');
INSERT INTO contacts (id, user_id, name, type, subgenre, listeners, twitter, instagram, discord, email, notes) VALUES (25, 'me', 'zuro', 'artist', NULL, 17000, '@zu344', NULL, NULL, NULL, NULL);
INSERT INTO contacts (id, user_id, name, type, subgenre, listeners, twitter, instagram, discord, email, notes) VALUES (26, 'me', '1deep', 'prod+artist', NULL, 2000, NULL, NULL, NULL, 'soundfixrecords@gmail.com', NULL);
INSERT INTO sends (user_id, contact_id, pack_id, channel, sent_at, status) VALUES ('me', 26, 1, 'mail', '2026-08-27', 'pendiente');
INSERT INTO contacts (id, user_id, name, type, subgenre, listeners, twitter, instagram, discord, email, notes) VALUES (27, 'me', 'BryceUnknwn', 'prod', NULL, NULL, '@bryceunknwn', NULL, NULL, NULL, NULL);
INSERT INTO sends (user_id, contact_id, pack_id, channel, sent_at, status) VALUES ('me', 27, 1, 'tw', '2026-08-27', 'pendiente');
INSERT INTO contacts (id, user_id, name, type, subgenre, listeners, twitter, instagram, discord, email, notes) VALUES (28, 'me', 'fivecrzy', 'prod', NULL, NULL, '@fivecrzy', NULL, NULL, NULL, NULL);
INSERT INTO contacts (id, user_id, name, type, subgenre, listeners, twitter, instagram, discord, email, notes) VALUES (29, 'me', 'Its2Ezzy', 'prod', NULL, NULL, '@TheReal2Ezzy', NULL, NULL, NULL, NULL);
INSERT INTO contacts (id, user_id, name, type, subgenre, listeners, twitter, instagram, discord, email, notes) VALUES (30, 'me', 'Nova', 'prod', NULL, NULL, '@SOUNDSBYNOVA1', NULL, NULL, NULL, NULL);
INSERT INTO contacts (id, user_id, name, type, subgenre, listeners, twitter, instagram, discord, email, notes) VALUES (31, 'me', 'Rio Leyva', 'prod', NULL, NULL, '@RioLeyva_', NULL, NULL, NULL, NULL);
INSERT INTO contacts (id, user_id, name, type, subgenre, listeners, twitter, instagram, discord, email, notes) VALUES (32, 'me', 'y2tnb', 'prod', NULL, NULL, '@y2tnb', NULL, NULL, NULL, NULL);
INSERT INTO contacts (id, user_id, name, type, subgenre, listeners, twitter, instagram, discord, email, notes) VALUES (33, 'me', '7ghto', 'prod', NULL, NULL, NULL, NULL, NULL, 'contact.7ghto@gmail.com', NULL);
INSERT INTO sends (user_id, contact_id, pack_id, channel, sent_at, status) VALUES ('me', 33, 1, 'mail', '2026-08-25', 'produciendo');
INSERT INTO contacts (id, user_id, name, type, subgenre, listeners, twitter, instagram, discord, email, notes) VALUES (34, 'me', 'Redda', 'prod+artist', NULL, 26000, '@reddadarko', NULL, NULL, NULL, NULL);
INSERT INTO contacts (id, user_id, name, type, subgenre, listeners, twitter, instagram, discord, email, notes) VALUES (35, 'me', 'reef', 'prod', NULL, NULL, '@whereisreef', NULL, NULL, NULL, NULL);
INSERT INTO contacts (id, user_id, name, type, subgenre, listeners, twitter, instagram, discord, email, notes) VALUES (36, 'me', 'egobreak', 'prod+artist', NULL, 166000, NULL, '@egobreak', NULL, NULL, NULL);
INSERT INTO contacts (id, user_id, name, type, subgenre, listeners, twitter, instagram, discord, email, notes) VALUES (37, 'me', 'matt proxy', 'prod+artist', NULL, 358000, '@mattprxy', NULL, NULL, NULL, NULL);
INSERT INTO sends (user_id, contact_id, pack_id, channel, sent_at, status) VALUES ('me', 37, 1, 'tw', '2026-08-27', 'pendiente');
INSERT INTO contacts (id, user_id, name, type, subgenre, listeners, twitter, instagram, discord, email, notes) VALUES (38, 'me', 'carbine', 'prod', NULL, NULL, '@saycarbine', NULL, NULL, NULL, NULL);
INSERT INTO sends (user_id, contact_id, pack_id, channel, sent_at, status) VALUES ('me', 38, 1, 'tw', '2026-08-27', 'pendiente');
INSERT INTO contacts (id, user_id, name, type, subgenre, listeners, twitter, instagram, discord, email, notes) VALUES (39, 'me', 'seanbaby', 'prod', NULL, NULL, '@1seanbaby', NULL, NULL, NULL, NULL);
INSERT INTO contacts (id, user_id, name, type, subgenre, listeners, twitter, instagram, discord, email, notes) VALUES (40, 'me', 'waera', 'prod', NULL, NULL, '@praizewa', NULL, NULL, NULL, NULL);
INSERT INTO sends (user_id, contact_id, pack_id, channel, sent_at, status) VALUES ('me', 40, 1, 'tw', '2026-08-27', 'pendiente');
INSERT INTO contacts (id, user_id, name, type, subgenre, listeners, twitter, instagram, discord, email, notes) VALUES (41, 'me', 'chris marek', 'prod', NULL, NULL, '@itschrismarek', NULL, NULL, NULL, NULL);
INSERT INTO contacts (id, user_id, name, type, subgenre, listeners, twitter, instagram, discord, email, notes) VALUES (42, 'me', 'nxah', 'prod', NULL, NULL, '@nxahoo', NULL, NULL, NULL, NULL);
INSERT INTO contacts (id, user_id, name, type, subgenre, listeners, twitter, instagram, discord, email, notes) VALUES (43, 'me', 'Punk Racks', 'prod+artist', NULL, 65000, '@punkracker', NULL, NULL, NULL, NULL);
INSERT INTO contacts (id, user_id, name, type, subgenre, listeners, twitter, instagram, discord, email, notes) VALUES (44, 'me', 'santamaria', 'prod', NULL, NULL, NULL, NULL, NULL, 'prod.santaa@gmail.com', NULL);
INSERT INTO sends (user_id, contact_id, pack_id, channel, sent_at, status) VALUES ('me', 44, 1, 'mail', '2026-08-25', 'pendiente');
